app/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views
from app.logbook.views_bdl import (deletebdl, editbdl, formbdl, 
bdl_save,bdl_draft_to,bdl_draft, mydocumentbdl, uploaddocument,
sendtoapprover, deletebdl, editbdl, viewdocument)

from app.logbook.views_medical import (deletemedical, deletemedical, editmedical, medical_draft_to, 
medical_save,medical_draft, formmedical, mydocumentmedical, sendtoapprovermedical, uploaddocument,  viewdocument, )

from app.logbook.views_entertainment import ( formentertainment, 
entertainment_save,enter_draft_to,enter_draft, mydocumententer, uploaddocument,
sendtoapproverenter, deleteenter, editenter, viewdocument)

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # The home page
    path('', views.index, name='home'),
    # The Logbook BDL 
    path('form-bdl', formbdl, name='form-bdl'),
    path('save-bdl', bdl_save, name='save-bdl'),
    path('bdl_draft_to', bdl_draft_to, name='bdl_draft_to'),
    path('bdl_draft', bdl_draft, name='bdl_draft'),
    path('send_to_approver/<str:doc_id>/', sendtoapprover, name='send_to_approver'),
    path('bdl-mydocument', mydocumentbdl, name='bdl-mydocument'),
    path('delete-bdl/<str:doc_id>', deletebdl, name='delete-bdl'),
    path('edit-bdl/<str:doc_id>', editbdl, name='edit-bdl'),
    path('view-bdl/<str:doc_id>', viewdocument, name='view-bdl'),
    # The Logbook BDL #


    # the Logbook Medical #

    path('form-medical', formmedical, name='form-medical'),
    path('medical-save', medical_save, name='medical-save'),
    path('medical_draft_to', medical_draft_to, name='medical_draft_to'),
    path('medical_draft', medical_draft, name='medical_draft'),
    path('send_to_approver_medical/<str:doc_id>/', sendtoapprovermedical, name='send_to_approver_medical'),
    path('medical-mydocument', mydocumentmedical, name='medical-mydocument'),
    path('delete-medical/<str:doc_id>', deletemedical, name='delete-medical'),
    path('edit-medical/<str:doc_id>', editmedical, name='edit-medical'),
    path('view-bdl/<str:doc_id>', viewdocument, name='view-bdl'),

    # the Logbook Medical #

    # the Logbook Entertaiment #

    path('form-entertaiment', formentertainment, name='form-entertaiment'),
    path('save-entertainment', entertainment_save, name='save-entertainment'),
    path('enter_draft_to', enter_draft_to, name='enter_draft_to'),
    path('enter_draft', enter_draft, name='enter_draft'),
    path('send_to_approver_enter/<str:doc_id>/', sendtoapproverenter, name='send_to_approver_enter'),
    path('enter-mydocument', mydocumententer, name='enter-mydocument'),
    path('delete-enter/<str:doc_id>', deleteenter, name='delete-enter'),
    path('edit-enter/<str:doc_id>', editenter, name='edit-enter'),
    path('view-bdl/<str:doc_id>', viewdocument, name='view-bdl'),
   
    # the Logbook Entertainment #

    


     path('upload-document/<str:doc_id>/', uploaddocument, name='upload-document'),
    
    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include(("app.urls", "app"), namespace="app"),)             # UI Kits Html files
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/templates/logbook/entertainment/draft.html
{% extends "layouts/base.html" %}

{% block title %} Draft BDL {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

      <div class="py-4">
          <nav aria-label="breadcrumb">
              <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                  <li class="breadcrumb-item"><a href="#"><span class="fas fa-home"></span></a></li>
                  <li class="breadcrumb-item"><a href="#">Form</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Draft Entertainment</li>
              </ol>
          </nav>
         
      </div>

      <div class="card border-light shadow-sm mb-4">
          <div class="card-body">
              <div class="table-responsive">
                  <table class="table table-centered table-nowrap mb-12 rounded">
                      <thead class="thead-light">
                          <tr>
                              <th class="border-0">Action</th>
                              <th class="border-0">Name</th>
                              <th class="border-0">Type</th>
                              <th class="border-0">DocumentId</th>
                              <th class="border-0">Remark</th>
                              <th class="border-0">IDR</th>
                              <th class="border-0">USD</th>
                              <th class="border-0">YEN</th>
                              <th class="border-0">BATH</th>
                              <th class="border-0">MYR</th>
                              <th class="border-0">SGD</th>
                              <th class="border-0">EURO</th>
                              
                          </tr>
                      </thead>
                      
                      <tbody>
                          <!-- Item -->
                          {% for list in bdldraft %}
                          <form action="{% url 'app:upload-document' list.doc_id %}" method="post" enctype="multipart/form-data">
                          <tr>
                            <td class="border-0">
                                <div class="btn-group">
                                    <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-0" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="icon icon-sm">
                                            <span class="fas fa-ellipsis-h icon-dark"></span>
                                        </span>
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    
                                    <div class="dropdown-menu py-0">
                                        <a class="dropdown-item rounded-top" href="{% url 'app:send_to_approver_enter' list.doc_id %}"><span class="far fa-paper-plane me-2"></span>Send To Approver</a>
                                        <a class="dropdown-item rounded-top" data-bs-toggle="modal" data-bs-target="#modal-default{{list.doc_id}}"><span class="fas fa-paperclip me-2"></span>Upload Receipt</a>
                                        <a class="dropdown-item rounded-top" href="{% url 'app:view-bdl' list.doc_id %}"><span class="fas fa-eye me-2"></span>View Details</a>
                                        <a class="dropdown-item" href="{% url 'app:edit-bdl' list.doc_id %}"><span class="fas fa-edit me-2"></span>Edit</a>
                                        <a class="dropdown-item text-danger rounded-bottom" href="{% url 'app:delete-enter' list.doc_id %}"><span class="fas fa-trash-alt me-2"></span>Remove</a>
                                    </div>
                                </div>
                              </td>
                              <td class="border-0"><a href="#" class="text-primary fw-bold">{{list.name_payment}}</a> </td>
                              <td class="border-0 fw-bold">{{list.doc_type}}</td>
                              <td class="border-0">
                                {{list.doc_id}}
                              </td>
                              <td class="border-0">
                                {{list.doc_remark}}
                              </td>
                              <td class="border-0">
                                {{list.total_payment_idr}}
                              </td>
                              <td class="border-0">
                                {{list.total_payment_usd}}
                              </td>
                              <td class="border-0">
                                {{list.total_payment_ypn}}
                              </td>
                              <td class="border-0">
                                {{list.total_payment_bath}}
                              </td>
                              <td class="border-0">
                                {{list.total_payment_myr}}
                              </td>
                              <td class="border-0">
                                {{list.total_payment_sgd}}
                              </td>
                              <td class="border-0">
                                {{list.total_payment_euro}}
                              </td>
                              
                          
                          <!-- End of Item -->
                          
                          
                            {% csrf_token %}
                          <div class="modal fade" id="modal-default{{list.doc_id}}" tabindex="-1" role="dialog" aria-labelledby="modal-default" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h2 class="h6 modal-title">Upload</h2>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <input type="file" name="documentes" multiple="multiple">
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-secondary">Accept</button>
                                      
                                    </div>
                                </div>
                            </div>
                        </div>
                      </form>
                    </tr>
                          {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
        </div>

   

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/logbook/entertainment/edit.html
{% extends "layouts/base.html" %}

{% block title %} Tables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %} Form BDL{% endblock stylesheets %}

{% block content %}

<div class="py-4">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
            <li class="breadcrumb-item"><a href="#"><span class="fas fa-home"></span></a></li>
            <li class="breadcrumb-item"><a href="#">Tables</a></li>
            <li class="breadcrumb-item active" aria-current="page">Entertainment</li>
        </ol>
    </nav>
    
</div>

<div class="row">
    <div class="col-12 mb-4">
        <div class="card border-light shadow-sm components-section">
            <div class="card-body">
                <form action="{% url 'app:save-entertainment' %}" method="POST">
                    {% csrf_token %}
                    <div class="row mb-4">
                        <div class="col-lg-2 col-sm-6">
                            <!-- Form -->
                            <div class="mb-3">
                                <label for="">Document ID</label>
                                <input type="text" class="form-control" name="id" value={{id}} required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="">NIK</label>
                                <input type="text" class="form-control" name="nik" value={{dataemp.emp_no}} required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="">Paid To</label>
                                <input type="text" class="form-control" name="paid" value={{dataemp.emp_name}} required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="">No Rekening Bank</label>
                                <input type="text" class="form-control" name="norek" value={{dataemp.bank_acct}}
                                    required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="">Bank Name</label>
                                <input type="text" class="form-control" name="bankname" value="BANK CENTRAL ASIA"
                                    required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <!-- End of Form -->
                        </div>
                        <div class="col-lg-4 col-sm-6">
                            <!-- Form -->
                            
                            
                            <div class="mb-3">
                                <label for="">Approver 1st:</label>
                                <input type="text" class="form-control" name="approver1"
                                    value="{{atasanpertama.emp_no}}-{{atasanpertama.emp_name}}" required disabled>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>

                            <div class="mb-3">
                                <label class="my-1 me-2" for="country">Budget Code:</label>

                                <select class="form-select" id="country" name="codebudget"
                                    aria-label="Default select example">
                                    <option selected>Open this select budget</option>
                                    {% for budget in codebudget %}
                                    <option value={{budget.budget_number}}-{{budget.gl_name}}>
                                        {{budget.budget_number}}-{{budget.gl_name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="birthday">Ent Date:</label>
                                <div class="input-group">
                                    <span class="input-group-text"><span class="far fa-calendar-alt"></span></span>
                                    <input name="enter_date" class="form-control" id="birthday" type="date"
                                        placeholder="dd/mm/yyyy" required>
                                </div>
                            </div>

                            <div class="mb-3">
                                <label for="">Currency:</label>
                                <input type="text" class="form-control" name="currency" value="IDR" required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="">Amount:</label>
                                <input type="text" class="form-control" name="ammount" required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <!-- End of Form -->
                        </div>
                        <div class="col-lg-4 col-sm-6">
                            <!-- Form -->

                            
                            
                            <div class="mb-3">
                                <label for="">Customer Name:</label>
                                <input type="text" class="form-control" name="customername" required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="">Position:</label>
                                <input type="text" class="form-control" name="position" required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="">Company:</label>
                                <input type="text" class="form-control" name="company" required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="">Kind of Business:</label>
                                <input type="text" class="form-control" name="kindofbusines" required>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            
                            <!-- End of Form -->
                        </div>
                        
                        <div class="card-footer">
                            <button class="btn btn-tertiary" type="submit"><span class="far fa-paper-plane me-2"
                                    id="fetch_student"></span>Add Transaction</button>

                        </div>
                </form>
            </div>



        </div>
    </div>
</div>
</div>

<div class="card border-light shadow-sm mb-2">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-centered  mb-0 rounded">
                <thead class="thead-light">
                    <tr>
                        <th class="border-0">Cutomer Name</th>
                        <th class="border-0">Position</th>
                        <th class="border-0">Company</th>
                        <th class="border-0">Kind of Busness</th>
                        <th class="border-0">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Item -->
                    {% for list in listenter %}
                    <tr>
                        <td class="border-0"><a href="#" class="text-primary fw-bold"></a>
                            {{list.customer_name}}
                        </td>
                        <td class="border-0 fw-bold"><span></span></span>
                            {{list.customer_position}}
                        </td>
                        <td class="border-0">
                            {{list.customer_company}}
                        </td>
                        <td class="border-0">
                            {{list.remark}}
                        </td>
                        
                        <td class="border-0">
                            <button class="btn btn-danger" type="submit"><span class="fa fa-minus-circle me-2"
                                    id="fetch_student"></span>Delete</button>
                        </td>
                    </tr>
                    <!-- End of Item -->
                    {% endfor %}


                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="card border-light shadow-sm mb-2">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-centered  mb-0 rounded">
                <thead class="thead-light">
                    <tr>
                       
                        <th class="border-0">Budget Code </th>
                        <th class="border-0">GL Name</th>
                        <th class="border-0">GL No</th>
                        <th class="border-0">Cost Center</th>
                        <th class="border-0">Curr</th>
                        <th class="border-0">Amount</th>
                        <th class="border-0">Description</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <!-- Item -->
                    {% for list in logbook_budget %}
                    <tr>
                        <td class="border-0"><a href="#" class="text-primary fw-bold"></a>
                           {{list.budget_code}}
                        </td>
                        <td class="border-0 fw-bold"><span></span></span>
                            {{list.gl_name}}
                        </td>
                        <td class="border-0">
                            {{list.gl_no}}
                        </td>
                        <td class="border-0">
                            {{list.div_code}}
                        </td>
                        <td class="border-0">
                            {{list.curr}}
                        </td>
                        <td class="border-0" name="amt">
                            {{list.amt}}
                        </td>
                       
                        
                        <td class="border-0">
                            {{list.remark}}
                        </td>
                       
                    </tr>
                    <!-- End of Item -->
                    {% endfor %}


                </tbody>
            </table>
        </div>
    </div>
</div>
<form action="{% url 'app:enter_draft_to' %}" method="POST">
    {% csrf_token %}
<div class="row">
    <div class="col-12 mb-4">
        <div class="card border-light shadow-sm components-section">
            <div class="card-body">
                
                <input type="hidden" id="custId" name="id" value={{id}}>
                <div class="my-4">
                    <label for="textarea">BDS Description:</label>
                    <textarea class="form-control" placeholder="BDS Description" id="textarea" name="bdsremark"
                        rows="4" required></textarea>
                </div>
                <div class="card-footer">
                    <button class="btn btn-tertiary" type="submit"><span class="far fa-paper-plane me-2"
                            id="fetch_student"></span>Add Transaction</button>

                </div>
            
            </div>
        </div>
    </div>
</div>
</form>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script type="application/javascript">
   
</script>

{% endblock javascripts %}

core/templates/logbook/entertainment/view.html

{% extends "layouts/base.html" %}
{% load static %}
{% block title %} Draft BDL {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}




<div class="row">
    <div class="col-12 mb-4">
        <div class="card border-light shadow-sm components-section">
            <div class="card-body">     
                <div class="row mb-4">
                    <div class="col-lg-4 col-sm-4">
                        {% for list in documents %}
                        <img src="{{list.docreceipt.url}}">
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}